# Generated by Django 4.2.3 on 2023-08-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articles_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
